### ISSUE TITLE
Please add a license?

### ISSUE THREAD

**Issue by smashedagainst** [TheFrozenFire/PHP-NBT-Decoder-Encoder#7]
Hi,

Would you please add a license? Like GPL or Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License? I'm making spigot minecraft server php files and would like to include your php class in it. Once I've got it done, I'll put it up here on Github.

I mention the share alike one because another useful class I'm including uses it: https://github.com/xPaw/PHP-Minecraft-Query

Thanks,
Chris

**Comment by TheFrozenFire** [comment]
Licensed it under MIT. Hopefully this works for you.

**Comment by smashedagainst** [comment]
Thanks, appreciated. With all the BS surrounding what happened with bukkit and wolveren, I want to keep things on the up and up.
